/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author camil
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        mnEmpleado = new javax.swing.JMenu();
        submnRegistrar = new javax.swing.JMenuItem();
        submnModificar = new javax.swing.JMenuItem();
        submnEliminarBusqueda = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        submnExit = new javax.swing.JMenuItem();
        mnProveedor = new javax.swing.JMenu();
        mnServicios = new javax.swing.JMenu();
        mnReservas = new javax.swing.JMenu();
        mnInformes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        mnEmpleado.setText("Empleado");

        submnRegistrar.setText("Registrar");
        submnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnRegistrarActionPerformed(evt);
            }
        });
        mnEmpleado.add(submnRegistrar);

        submnModificar.setText("Modificar");
        submnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnModificarActionPerformed(evt);
            }
        });
        mnEmpleado.add(submnModificar);

        submnEliminarBusqueda.setText("Eliminar / Busqueda ");
        mnEmpleado.add(submnEliminarBusqueda);
        mnEmpleado.add(separador);

        submnExit.setText("Exit");
        mnEmpleado.add(submnExit);

        barraMenu.add(mnEmpleado);

        mnProveedor.setText("Proveedor");
        barraMenu.add(mnProveedor);

        mnServicios.setText("Servicios");
        barraMenu.add(mnServicios);

        mnReservas.setText("Reservas");
        barraMenu.add(mnReservas);

        mnInformes.setText("Informes");
        barraMenu.add(mnInformes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnRegistrarActionPerformed
        EmpleadoRegistrar empleadoRegistrar = new EmpleadoRegistrar(this, true);
        empleadoRegistrar.setVisible(true);
    }//GEN-LAST:event_submnRegistrarActionPerformed

    private void submnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnModificarActionPerformed
        EmpleadoActualizar empleadoActualizar = new EmpleadoActualizar(this,true);
        empleadoActualizar.setVisible(true);
    }//GEN-LAST:event_submnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu mnEmpleado;
    private javax.swing.JMenu mnInformes;
    private javax.swing.JMenu mnProveedor;
    private javax.swing.JMenu mnReservas;
    private javax.swing.JMenu mnServicios;
    private javax.swing.JPanel panel;
    private javax.swing.JPopupMenu.Separator separador;
    private javax.swing.JMenuItem submnEliminarBusqueda;
    private javax.swing.JMenuItem submnExit;
    private javax.swing.JMenuItem submnModificar;
    private javax.swing.JMenuItem submnRegistrar;
    // End of variables declaration//GEN-END:variables
}
