/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cargo;
import Modelo.Conexion;
import Modelo.ControladorAdministrador;
import Modelo.Personal;
import Modelo.Usuario;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Modelo.CifrarContraseña;
import Modelo.Comuna;
import Modelo.Perfil;
import java.sql.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author camil
 */
public class EmpleadoRegistrar extends javax.swing.JDialog {

    Conexion conexion = new Conexion();
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public EmpleadoRegistrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarCombobox();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        panel = new javax.swing.JPanel();
        lbEmpleado = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        lbRut = new javax.swing.JLabel();
        textRut = new javax.swing.JTextField();
        lbApellidoPaterno = new javax.swing.JLabel();
        textApellidoPaterno = new javax.swing.JTextField();
        lbApellidoMaterno = new javax.swing.JLabel();
        textApellidoMaterno = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        lbFechaNacimiento = new javax.swing.JLabel();
        lbTelefono2 = new javax.swing.JLabel();
        textTelefono2 = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        lbTelefono = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbCrearUsuario = new javax.swing.JLabel();
        lbContraseña = new javax.swing.JLabel();
        lbConfirmar = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox<>();
        lbPerfil = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pwContraseña = new javax.swing.JPasswordField();
        pwConfirmarContraseña = new javax.swing.JPasswordField();
        textFechaNacimiento = new javax.swing.JTextField();
        lbCalle = new javax.swing.JLabel();
        textCalle = new javax.swing.JTextField();
        lbSueldo = new javax.swing.JLabel();
        lbDepartamento = new javax.swing.JLabel();
        textSueldo = new javax.swing.JTextField();
        textDepartamento = new javax.swing.JTextField();
        lbNumero = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();
        lbComuna = new javax.swing.JLabel();
        cmbComuna = new javax.swing.JComboBox<>();
        lbCargo = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbEmpleado.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbEmpleado.setText("Datos Empleado");
        panel.add(lbEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        lbNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbNombre.setText("Nombre:");
        panel.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        textNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panel.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 190, -1));

        lbRut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbRut.setText("Rut:");
        panel.add(lbRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 78, -1, -1));

        textRut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panel.add(textRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 72, 300, -1));

        lbApellidoPaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbApellidoPaterno.setText("Apellido Paterno");
        panel.add(lbApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        textApellidoPaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panel.add(textApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, -1));

        lbApellidoMaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbApellidoMaterno.setText("Apellido Materno");
        panel.add(lbApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        textApellidoMaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panel.add(textApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 190, -1));

        lbEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbEmail.setText("Email");
        panel.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        textEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panel.add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 190, -1));

        lbFechaNacimiento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbFechaNacimiento.setText("Fecha de Nacimiento");
        panel.add(lbFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        lbTelefono2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTelefono2.setText("Telefono 2:");
        panel.add(lbTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        textTelefono2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panel.add(textTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 180, -1));

        textTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panel.add(textTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 180, -1));

        lbTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTelefono.setText("Telefono 1:");
        panel.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));
        panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 632, 10));

        lbCrearUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbCrearUsuario.setText("Crear Usuario");
        panel.add(lbCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        lbContraseña.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbContraseña.setText("Contraseña:");
        panel.add(lbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        lbConfirmar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbConfirmar.setText("Confirmar Contraseña:");
        panel.add(lbConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        cmbPerfil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panel.add(cmbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 160, -1));

        lbPerfil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbPerfil.setText("Perfil:");
        panel.add(lbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        panel.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panel.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));
        panel.add(pwContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 189, -1));
        panel.add(pwConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 189, -1));
        panel.add(textFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 180, -1));

        lbCalle.setText("Calle");
        panel.add(lbCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));
        panel.add(textCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 190, -1));

        lbSueldo.setText("Sueldo");
        panel.add(lbSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        lbDepartamento.setText("Departamento");
        panel.add(lbDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));
        panel.add(textSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 180, -1));
        panel.add(textDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 180, -1));

        lbNumero.setText("Numero");
        panel.add(lbNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));
        panel.add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 190, -1));

        lbComuna.setText("Comuna");
        panel.add(lbComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        panel.add(cmbComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 190, -1));

        lbCargo.setText("Cargo");
        panel.add(lbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        panel.add(cmbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void llenarCombobox(){
        llenarComboboxComuna();
        llenarComboboxCargo();
        llenarComboboxPerfil();
    }
    
    private void llenarComboboxCargo(){
        Cargo cargo = new Cargo();
        DefaultComboBoxModel modeloCargo = new DefaultComboBoxModel(cargo.mostrarCargo());
        cmbCargo.setModel(modeloCargo);
    }
    
    private void llenarComboboxPerfil(){
        Perfil perfil = new Perfil();
        DefaultComboBoxModel modeloPerfil = new DefaultComboBoxModel(perfil.mostrarPerfil());
        cmbPerfil.setModel(modeloPerfil);
    }
    
    private void llenarComboboxComuna(){
        Comuna comuna = new Comuna();
        DefaultComboBoxModel modeloComuna = new DefaultComboBoxModel(comuna.mostrarComuna());
        cmbComuna.setModel(modeloComuna);
    }
    
    
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Personal personal = new Personal();
        Usuario usuario = new Usuario();
        ControladorAdministrador conAdmin = new ControladorAdministrador();
        
        String contraseña = new String(pwContraseña.getPassword()); //transformar contraseña a String
        String confirmarContraseña = new String(pwConfirmarContraseña.getPassword());
        
        if(textRut.getText().equals("") || textApellidoPaterno.getText().equals("") || textCalle.getText().equals("") || 
                textEmail.getText().equals("") || textNombre.getText().equals("") || textNumero.getText().equals("") ||
                textSueldo.getText().equals("") || textTelefono.getText().equals("") || textTelefono2.getText().equals("") ||
                contraseña.equals("") || confirmarContraseña.equals("")){
                JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
        } else {
            if(contraseña.equals(confirmarContraseña)){
                //if(conAdmin.verificarUsuario(textRut.getText()) == 0){
                    if(conAdmin.comprobarEmail(textEmail.getText())){
                        
                        String nuevaContraseña = CifrarContraseña.md5(contraseña);//Cifrar contraseña a sha1
                       
                        
                        personal.setRut(textRut.getText());
                        personal.setNombre(textNombre.getText());
                        personal.setApellidoPaterno(textApellidoPaterno.getText());
                        personal.setApellidoMaterno(textApellidoMaterno.getText());
                        personal.setF_contacto1(Integer.parseInt(textTelefono.getText()));
                        personal.setF_contacto2(Integer.parseInt(textTelefono2.getText()));
                        personal.setEmail(textEmail.getText());
                        personal.setSueldo(Integer.parseInt(textSueldo.getText()));
                        personal.setCalle(textCalle.getText());
                        personal.setNumero(Integer.parseInt(textNumero.getText()));
                        personal.setDepto(Integer.parseInt(textDepartamento.getText()));
                        //personal.setId_cargo(cmbCargo.getSelectedIndex());
                       // personal.setId_cargo(Integer.parseInt(cmbCargo.getSelectedItem().toString()));//Duda
                       //personal.setId_cargo(cmbCargo.getSelectedItem().toString());
                      
                       
                        System.out.println(cmbCargo.getSelectedItem().toString());
// personal.setId_comuna(cmbComuna.getSelectedIndex());
                        personal.setId_comuna(Integer.parseInt(cmbComuna.getSelectedItem().toString()));
                        personal.setId_perfil(Integer.parseInt(cmbPerfil.getSelectedItem().toString()));
                        //personal.setId_perfil(cmbPerfil.getSelectedIndex());
                        personal.setFecha_nac(Date.valueOf(textFechaNacimiento.getText()));
                        usuario.setRut(textRut.getText());
                        usuario.setClave(nuevaContraseña);
                        usuario.setId_perfil(Integer.parseInt(cmbPerfil.getSelectedItem().toString()));
                        
                        if(conAdmin.Registrar(personal)){
                            if(conAdmin.RegistrarUsuario(usuario)){
                                JOptionPane.showMessageDialog(null, "Registrado correctamente");
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Error");
                            }
                        } 
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "El correo no es correcto");
                    }
                //}
                //else {
                  //      JOptionPane.showMessageDialog(null, "Ya existe un usuario con ese rut");
                //}
            }
            else {
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmpleadoRegistrar dialog = new EmpleadoRegistrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JComboBox<String> cmbComuna;
    private javax.swing.JComboBox<String> cmbPerfil;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbApellidoMaterno;
    private javax.swing.JLabel lbApellidoPaterno;
    private javax.swing.JLabel lbCalle;
    private javax.swing.JLabel lbCargo;
    private javax.swing.JLabel lbComuna;
    private javax.swing.JLabel lbConfirmar;
    private javax.swing.JLabel lbContraseña;
    private javax.swing.JLabel lbCrearUsuario;
    private javax.swing.JLabel lbDepartamento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmpleado;
    private javax.swing.JLabel lbFechaNacimiento;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JLabel lbRut;
    private javax.swing.JLabel lbSueldo;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTelefono2;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField pwConfirmarContraseña;
    private javax.swing.JPasswordField pwContraseña;
    private javax.swing.JTextField textApellidoMaterno;
    private javax.swing.JTextField textApellidoPaterno;
    private javax.swing.JTextField textCalle;
    private javax.swing.JTextField textDepartamento;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textFechaNacimiento;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textRut;
    private javax.swing.JTextField textSueldo;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JTextField textTelefono2;
    // End of variables declaration//GEN-END:variables
}
